project:
  type: website

website:
  title: "CIS112 Database Concepts"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - assignments.qmd
      - policies.qmd

format:
  html:
    theme: 
      light: quartz
      dark: darkly
    css: styles.css
    toc: true



