---
title: "Database Concepts"
subtitle: CIS 112. Washington & Jefferson College. Fall 2024.
---

::: {#hero-banner}

:::: {.overlay .content}

**Meeting Time: MWF 1:00-2:10pm**

Dr. Ladd’s Student Drop-In Hours: M 11:30am–12:30pm, Tu & Th 1:30–3:30pm in TECH 201
or email for appointment, jladd@washjeff.edu

PAL Tutoring Hours: 7-10pm Sunday–Thursday in the CIS Lounge (TECH 217)  
[Tutor bios and additional info](https://mywj.washjeff.edu/knowledgebase/cis-peer-tutoring/department/computing-and-information-studies)

::::

:::

## Course Description

Databases power so much of our daily lives: your school records are kept in a database, the social media posts you create are recorded and tracked in databases, and your bank keeps your balance and transactions in a database. They are an essential tool for organizing and sharing information across large systems.

This course will provide an overview of the role of databases within a variety of academic, business, and governmental organizations, and an introduction to database design and management. You will create databases related to your major fields or secondary course of study using both small business and enterprise-class database management systems.

## Learning Goals

At the end of this course, you will be able to:

- Describe and identify the functions of a Database Management System in both design and management
- Understand the fundamental concepts ubiquitous to Database Management Systems
- Create databases using common languages and management systems such as SQL and Postgres
- Design and develop complex database systems using common data forms and normalization techniques

