---
title: "Course Policies"
---

## Shared Expectations for this Class

### Preparation and Pacing

 We will cover a lot of material during the semester, and you will have many opportunities to discuss complex ideas with your peers. Some of you may be entering the classroom with more advanced prior knowledge of databases and related topics, while others may be encountering these concepts for the first time. Group learning and discussion are key aspects of this course. This means that we all need to do our part to be prepared for each class, and to foster a positive and inquisitive learning environment.

In between classes you should:

- Review your notes from previous classes
- Read the assigned readings for that day
- Refer to this site for updates to the [schedule](/CIS112/schedule)
- DO NOT wait until the last minute to begin your assignments
- EMAIL your instructor with any questions. Ask lots of questions!

Each class must create its own learning community as the result of shared efforts on the part of all members. It is your responsibility as a member of this learning community to help your fellow students by attending class and turning in assignments on time. If you must miss a class or turn in an assignment late, please let me know beforehand so that we may work out a way for you to make up the work. You do *not* need a doctor's note or other written excuse, but please let me know if there are special circumstances that may prevent you from completing a large amount of coursework.

### Attendance & Participation

Good participation should be understood as consistent and thoughtful contribution to the classroom community, an engagement with course materials and conversations, and a general responsiveness to (and respect for) one’s fellow students and instructor. This isn’t an accounting of how often you speak in class. Instead, it’s about what you offer to the intellectual life of the class, and everyone contributes to this on-going work in different ways. Particularly because so much of the class will consist of hands-on work, you’ll get participation credit simply for attending class and doing the work with care.

Attending class is not optional: regular attendance is necessary to succeed in this course. Each day will have new content, activities, and learning opportunities. You'll want to attend as much as possible to avoid falling behind. **If you have to miss class for any reason, please let me know in advance**, especially if you have to miss more than one class in a row. Missing class is not an excuse for missing assignment deadlines, being unprepared for the next class session, or falling behind on the daily quizzes. You are responsible for keeping up-to-date with the work of the course or for communicating with me about unexpected circumstances which change your ability to do so. You can always reach out to me or a classmate to find out what you missed. We're all in this together, and I'll do my best to make sure no one falls behind.

Some class days on the schedule are marked with a double asterisk (\*\*): this indicates extremely important content without which you cannot be successful in the rest of the course. If you must miss any portion of a class session on dates indicated with a double asterisk, you must schedule a meeting with me to cover what you missed **before the next class you attend**. In each instance, *failure to do so will reduce your final letter grade by one step* (e.g., an A becomes an A-, a B- becomes a C+, etc.).

#### Instructor Absence

If I have to miss class due to illness or any other reason, I will let you know as soon as possible via email. I'll also post any relevant materials on Sakai or on this website, and my email will let you know what you need to do. It's a good idea to check your email at least once a day, since that's the primary way I'll keep in touch about any changes to the schedule.

### Lateness and Extensions

All assignments are due by the start of each class. I know that things don't always go according to plan. If you need an extension, simply ask for one (by email), and you'll almost always receive it. You don't need an excuse to receive an extension!

However, you **must ask for the extension *at least* 24 hours before the assignment deadline**. When you email about an extension, please propose a new deadline for the assignment (a good rule of thumb is 2 or 3 days after the original deadline). Any work received late without an agreed-upon extension will be penalized one point per day.

But keep in mind: **I cannot accept any assignment more than one week late.** This a fast-moving course, and I want to ensure that everyone stays on track. Assignments more than one week late will receive a 0.

### Academic Honesty and Integrity

In this course, as in all courses, you are expected to adhere to W&J's standards of academic honesty and integrity. You should refer to the College Catalog on MyW&J for the details of this policy and how cases of academic misconduct are handled.

In general, when completing writing and coding assignments, ensure all work is your own, and give credit where it is due in your citations. Likewise do not collaborate on quizzes, tests, or homework assignments unless explicitly granted permission. If you have any concerns about whether you might have plagiarized (e.g., if you’re not sure about some particular rule), please get in touch with me immediately---I will gladly discuss the matter with you.

#### Academic Honesty & Coding

These standards of academic integrity apply to coding as well as other kinds of classwork. Citation isn’t just for papers! It’s very common, and perfectly permissible, to borrow code snippets from a classmate or from somewhere online. When you do, make sure to include a note in your code’s comments about where the code came from. Keep in mind that this includes the use of any automated writing or code assistants like ChatGPT—any use of such programs should be cited like any website, with a link to the chat record. Not only will this let you give appropriate intellectual credit and avoid plagiarism, it will also help you remember what you were trying to do when you revise your code later.

With regard to ChatGPT, Gemini, GitHub Copilot, or any related generative AI systems, keep in mind that in this class *you are only permitted to use these systems to help with your code, **never** with your writing*. If you do use a code assistant to help, you **must** cite what you used in a comment and include a link to the chat record. **And keep in mind that these tools may not give you the best advice! It’s always better to work from our course materials or ask a classmate for help.**

### Names and Pronouns

Everyone has the right to be addressed as they feel most comfortable. It’s hard to learn if you cringe every time I call on you or address you in communication. I will ask everyone at the beginning of the semester to tell me their preferred name, pronunciation, and the pronouns they use. I will do my very best to get it right.  Please do not feel the need to change your name or pronouns to “make it easy” for me, and please correct me if I get it wrong! This policy goes for everyone---use the names and pronouns dictated by the person to whom they belong. Also, our personal growth does not always align with the semester system: If your name or pronoun changes part way through the class, please send me an update!

### Class Technology

Please be respectful with your use of laptops and technology in class. I request that you only use them for class related purposes, as I and others may find them distracting (For example, no email or social media should be open in your browser tabs!). Cell phones should be kept silent and put away, and you can expect the same from me.

## Important Resources for this Class and Your College Journey

### Mental Health

What we do in college is not easy, on many fronts. Students are challenged with feelings of depression, anxiety, and self harm at astonishingly high rates. Learning is hard, and you will likely be challenged in college in ways that you haven’t experienced before. Learning while life is hard is even harder. Please take care of yourself. Drink water, eat well, and get more than seven hours of sleep. Have some hobbies, but don’t feel the need to do *everything*. If you are feeling depressed, withdrawn, anxious, like an impostor, or you are having specific problems with harassment, assault, bias, etc., please seek help. There are many resources on campus, and my door and email are always open.

Please also consider contacting the [Student Counseling Center](https://www.washjeff.edu/student-life/student-health-and-counseling-center/) (724) 223-6107 or the 24/7/365 Counseling Support Line (833) 434-1217, for support if you’re feeling stressed, overwhelmed, anxious, depressed, lost, or are struggling with personal issues.  Services are free and confidential. Students have access to free, confidential counseling, self-help, meditation programs, online therapy and crisis counseling via (833) 434-1217 or by registering with uWill.

### Disability Support Services

Disability Support Services Washington & Jefferson College is committed to providing academic accommodations for students with disabilities.  Accommodations are available for students with physical disabilities, learning disabilities, and mental health diagnoses that meet the definition of a disability under the Americans with Disabilities Act.  Students who believe they may qualify for academic accommodations should contact the Director for Academic Success on the Clark Family Library Ground Floor at (724) 223-6008 or <dss@washjeff.edu>.   For students who are already registered with Disability Support Services, please share your letters of accommodation with your professors as soon as possible.  Your letter serves as an opportunity for professors and students to work together and ensure that your accommodations are successfully delivered throughout the term.

### W&J Library

I highly recommend that you make use of the W&J Library resources while navigating your essays this semester. That includes not only primary literature, access to databases, and book references, but also the friendly members of the library staff. They are excellent resources for finding information efficiently, or learning what you can access through W&J subscriptions that might not be freely available on the internet. The W&J Library homepage is <https://libguides.washjeff.edu/home>.

### Writing Center

Staffed by student Peer Writing Tutors, the Writing Center is a free resource available to all W&J students. Writing Tutors from many majors help writers one-on-one in all phases of the writing process, from deciphering assignments, to discussing ideas, to developing an argument, to finalizing a draft. Because proofreading is a last step in that process, you should leave plenty of time (like at least a week) for getting your ideas right before expecting proofreading help. Consultants also can help writers with personal documents, like job and internship applications. The Center welcomes student writers with all varieties of backgrounds and college preparation, including multilingual writers. Please visit the Writing Center's page (<https://mywj.washjeff.edu/office/writing-center>) on MyW&J for specific information regarding hours of availability and how to schedule an appointment.

### Cautions regarding copyright and licensing

All documents provided to you (i.e. syllabus, paper prompts, tests, etc...) are the property of the instructor or author. It is a violation of intellectual property to post these online (especially to websites promoting copying/cheating) or to provide them to students not in our class or in future classes. Your papers are your property, and while you can do with them as you wish, it may be a violation of academic integrity to make them available to others who might use them for plagiarism. Basically, keep course materials and your work to yourself except in the process of editing and peer review.

### Inclusion and Diversity

This course is open to anyone interested in databases and related technologies. It is my intent to make all students feel welcome and served in this course by addressing their learning needs. We all (including myself) are continuously learning about different lived experiences. In this course, if you encounter anything said (intentionally or unintentionally) that made you feel uncomfortable, please talk to me about it. If your learning is impacted by your background, or any life event going on outside of class, feel free to talk to me. Even if you choose not to share details, I would be happy to direct you to the right resources on campus.

I acknowledge that each of you has their own specific life history, family context, identity, body—and that these realities have an impact on how you understand and interact with our course materials. Therefore, I ask you to generally familiarize yourself with the content of our discussions ahead of time, and if for any reason you believe you will be unable to participate in a discussion of certain themes or elements, please contact me beforehand and/or seek the support of any of the formal or informal resources available to you on campus, some of which are included in this syllabus. I look forward to creating a safe learning environment together this semester!

## Grading Scale

Letter Grade|Point Total
---|---
A|93-100
A-|90-92
B+|87-89
B|83-86
B-|80-82
C+|77-79
C|73-76
C-|70-72
D+|67-69
D|63-66
D-|60-62
F|<60

: {.striped .hover}
